





var questions = [
    "Navn og alder:",
    "Køn/Pronominer:",
    "Email:",
    "Mobil:",
    "Evt. Instagram / Andet:",
    "Jeg ryger:",
    "Mine hobbyer:",
    "Mine favoritserier:",
    "Andre tilføjelser:",
];


var answerForms = {}

var imgelements = []

// for sending the email
var appForm = document.getElementById("application-form");
var fromName = document.getElementById("applicant-name");
var fromData = document.getElementById("application-data");

// for creating the application
var submitButton = document.getElementById("submit-email-button");
var imgparent = document.getElementById("picture-holder");
var qparent = document.getElementById("question-holder");
var template = document.getElementById("question-template");
var thankyoumessage = document.getElementById("thankyoumessage");

function ToggleImageFullscreen(buttonElement)
{
    if (buttonElement.className != "fullscreenImage")
    {
        buttonElement.className = "fullscreenImage";
    }
    else
    {
        buttonElement.className = "picbutton";
    }
}

function AssignPictures()
{
    for (let i = 0; i < 5; i++) {
        var butElement = document.createElement("button")
        butElement.className = "picbutton";
        
        var imgElement = document.createElement("img")
        butElement.append(imgElement);
        
        imgelements[i] = butElement;
        butElement.onclick = function t() {
            ToggleImageFullscreen(imgelements[i]);
        };
        
        imgElement.src = `roomiefiles/picture${i}.png`;
        imgElement.className = "picture";

        imgparent.append(butElement);
    }
}
AssignPictures();

function AssignQuestions()
{
    for (let i = 0; i < questions.length; i++) {
        var qElement = template.cloneNode(true);
        var textEl = qElement.getElementsByClassName("whitetext")[0];
        textEl.innerText = questions[i];

        var form = qElement.getElementsByClassName("input")[0];
        answerForms[questions[i]] = form;

        qElement.removeAttribute("hidden");
        qparent.append(qElement);
    }
    template.remove();
}
AssignQuestions();





function SubmitEmail()
{
    submitButton.remove();
    qparent.remove();

    //console.log(GetEmailText())
    SendAutoGeneratedEmail();
}


const serviceID = 'RoomieApp_a1a3';
const templateID = 'template_owiw4am';

function SendAutoGeneratedEmail()
{
    thankyoumessage.innerText = "Sender email...";

    // workaround to get the correct email form structure
    fromName.value = answerForms[questions[0]].value;
    fromData.value = GetEmailText();

    emailjs.sendForm(serviceID, templateID, appForm)
    .then(() => {
        thankyoumessage.innerText = "Tak for din henvendelse! Jeg vender tilbage til dig snart :)";
    }, (err) => {
        thankyoumessage.innerText = "Noget gik galt med at sende emailen. Prøv igen om lidt.";
    });


}

function GetEmailText()
{
    var text = "";
    for (let i = 1; i < questions.length; i++) {
        var form = answerForms[questions[i]];
        text += " ◘ ";
        text += questions[i];
        text += " | ";
        text += form.value;
        text += "  ";
    }
    return text;
}










